apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "JW587jqfWpa9lgDiKpi0pABeFzjl7wLg2SD0C6oyQXEvxJNPBmyDxVWz5mepVihc\nONtvotGPgN5mBcSvrOldTwiJkf2QLcz7HCLtynRiyk6tf1CwXb9lEW9xTxlaTwkA\nwF1m9IMs5sBG+/UuGYQQQcQCf+hlmTzFG7y3kuaxgi8="
