apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "FsUoenQCj31jtTk22ePDZ3JHEundsttzSRNvtgJLxNDvlEALORNOuL8w1gkPuqJ/\njzvratED04r+J6UaX9ltCYj+b0PvLmCzO7u7Sit7iOkQN2b+Yfk5uoLzxUXHPO5Y\n2iYhuKAhOsRLQU2JXxGHVqeQyyOvlrvim78o9rY6RMA="
