apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "9NSWQI0tzhICKFw89i5EpLat3mY025ycum0Hz2vg3W03UZg6wt/Mzxg/Fpzh1zLy\nMgVs3P2CJqf5edzApRV9j7uxSghESHkBTuoUFsQq4fM1wq/lz8PK4TGo7mHZIyet\n2WaNRt0m1wWCQjG2FT+biU48Ibuedq1Ewhm6WDMMpxo="
